/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author adicom
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemInsert = new javax.swing.JMenuItem();
        MenuItemSearch = new javax.swing.JMenuItem();
        MenuItemEdit = new javax.swing.JMenuItem();
        MenuItemDelet = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItemList = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("مدیریت فیلم");

        jMenu1.setText("عملیات");

        MenuItemInsert.setText("ثبت فیلم");

        MenuItemInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemInsertActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemInsert);

        MenuItemSearch.setText("جستوجوی فیلم");

        MenuItemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSearchActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemSearch);

        MenuItemEdit.setText("ویرایش");

        MenuItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEditActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemEdit);

        MenuItemDelet.setText("حذف");

        MenuItemDelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDeletActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemDelet);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("گزارش گیری");

        MenuItemList.setText("لیست");
        jMenu2.add(MenuItemList);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSearchActionPerformed
      JFrameSearch jFrameSearch = new JFrameSearch();
        jFrameSearch.setVisible(true);
    }//GEN-LAST:event_MenuItemSearchActionPerformed

    private void MenuItemInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemInsertActionPerformed
        JFrameInsert jFrameInsert = new JFrameInsert();
        jFrameInsert.setVisible(true);
    }//GEN-LAST:event_MenuItemInsertActionPerformed

    private void MenuItemDeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDeletActionPerformed
        JFrameEdit jFrameEdit = new JFrameEdit();
        jFrameEdit.setVisible(true);
    }//GEN-LAST:event_MenuItemDeletActionPerformed

    private void MenuItemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEditActionPerformed
        JFrameEdit jFrameEdit = new JFrameEdit();
        jFrameEdit.setVisible(true);
    }//GEN-LAST:event_MenuItemEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemDelet;
    private javax.swing.JMenuItem MenuItemEdit;
    private javax.swing.JMenuItem MenuItemInsert;
    private javax.swing.JMenuItem MenuItemList;
    private javax.swing.JMenuItem MenuItemSearch;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
